# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=26.2
	short_minecraft_version=26.2
	loader_version=0.19.3

# Mod Properties
	mod_version = 0.2.2
	maven_group = me.basiqueevangelist
	archives_base_name = worldspecificviewdistance

# Dependencies
	# https://fabricmc.net/develop/
	fabric_version=0.154.2+26.2
    # https://github.com/TerraformersMC/ModMenu/releases
	modmenu_version=20.0.1
    # https://modrinth.com/mod/cardinal-components-api/versions
	cca_version=8.0.1
